# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7673330418ac42ea42867896b0ed5461627685033c374f0654f31d19c59aaf7348ba2e5de63967c67d63b83bb9f0b146707b231535ab3c64c7656dba536f60e9

test:
  secret_key_base: 538cc8142aad9992bc8a36acf2d4576dfa91fc1bbcd41e50797b06136640d09b924b95ab16dd214f0f762ae4ad367187755b9e100657c157caeaaaa52bddbd6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
